FROM httpd:2.4
COPY ./mentor-on-demand-ui/index.html /usr/local/apache2/htdocs/index.html
COPY ./mentor-on-demand-ui/main.js /usr/local/apache2/htdocs/main.js
COPY ./mentor-on-demand-ui/polyfills.js /usr/local/apache2/htdocs/polyfills.js
COPY ./mentor-on-demand-ui/runtime.js /usr/local/apache2/htdocs/runtime.js
COPY ./mentor-on-demand-ui/styles.js /usr/local/apache2/htdocs/styles.js
COPY ./mentor-on-demand-ui/vendor.js /usr/local/apache2/htdocs/vendor.js

COPY ./mentor-on-demand-ui/assets/css/bootstrap.css  /usr/local/apache2/htdocs/bootstrap.css
COPY ./mentor-on-demand-ui/assets/css/bootstrap.min.css /usr/local/apache2/htdocs/bootstrap.min.css
COPY ./mentor-on-demand-ui/assets/css/br-default-theme.css /usr/local/apache2/htdocs/br-default-theme.css
COPY ./mentor-on-demand-ui/assets/css/br-movie-theme.css /usr/local/apache2/htdocs/br-movie-theme.css
COPY ./mentor-on-demand-ui/assets/css/datepicker.css /usr/local/apache2/htdocs/datepicker.css
COPY ./mentor-on-demand-ui/assets/css/fullcalendar.css /usr/local/apache2/htdocs/fullcalendar.css
COPY ./mentor-on-demand-ui/assets/css/jquery-ui.css /usr/local/apache2/htdocs/jquery-ui.css
COPY ./mentor-on-demand-ui/assets/css/styles.css /usr/local/apache2/htdocs/styles.css

COPY ./mentor-on-demand-ui/ajax-loader.gif /usr/local/apache2/htdocs/ajax-loader.gif
COPY ./mentor-on-demand-ui/banner.png /usr/local/apache2/htdocs/banner.png
COPY ./mentor-on-demand-ui/favicon.ico /usr/local/apache2/htdocs/favicon.ico
COPY ./mentor-on-demand-ui/grid_topbg.jpg /usr/local/apache2/htdocs/grid_topbg.jpg
COPY ./mentor-on-demand-ui/search.jpg /usr/local/apache2/htdocs/search.jpg
COPY ./mentor-on-demand-ui/search_up.jpg /usr/local/apache2/htdocs/search_up.jpg
COPY ./mentor-on-demand-ui/sign_in.png /usr/local/apache2/htdocs/sign_in.png
COPY ./mentor-on-demand-ui/ui-icons_444444_256x240.png /usr/local/apache2/htdocs/ui-icons_444444_256x240.png
COPY ./mentor-on-demand-ui/ui-icons_555555_256x240.png /usr/local/apache2/htdocs/ui-icons_555555_256x240.png
COPY ./mentor-on-demand-ui/ui-icons_777620_256x240.png /usr/local/apache2/htdocs/ui-icons_777620_256x240.png
COPY ./mentor-on-demand-ui/ui-icons_777777_256x240.png /usr/local/apache2/htdocs/ui-icons_777777_256x240.png
COPY ./mentor-on-demand-ui/ui-icons_cc0000_256x240.png /usr/local/apache2/htdocs/ui-icons_cc0000_256x240.png
COPY ./mentor-on-demand-ui/ui-icons_ffffff_256x240.png /usr/local/apache2/htdocs/ui-icons_ffffff_256x240.png


COPY ./mentor-on-demand-ui/assets/js/jquery.min.js  /usr/local/apache2/htdocs/assets/js/jquery.min.js
COPY ./mentor-on-demand-ui/assets/js/jquery-1.12.4.js /usr/local/apache2/htdocs/assets/js/jquery-1.12.4.js
COPY ./mentor-on-demand-ui/assets/js/jquery-ui.js /usr/local/apache2/htdocs/assets/js/jquery-ui.js
COPY ./mentor-on-demand-ui/assets/js/bootstrap.min.js /usr/local/apache2/htdocs/assets/js/bootstrap.min.js
COPY ./mentor-on-demand-ui/assets/js/jquery_004.js /usr/local/apache2/htdocs/assets/js/jquery_004.js


COPY ./mentor-on-demand-ui/assets/images/flags/de.png /usr/local/apache2/htdocs/assets/images/flags/de.png
COPY ./mentor-on-demand-ui/assets/images/flags/en.png /usr/local/apache2/htdocs/assets/images/flags/en.png
COPY ./mentor-on-demand-ui/assets/images/flags/fr.png /usr/local/apache2/htdocs/assets/images/flags/fr.png

COPY ./_htaccess /usr/local/apache2/htdocs/
COPY ./httpd.config /usr/local/apache2/conf/httpd.conf